#line 2 "Kernel/Parsers/MSLScanner.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <fstream>
using std::istream;
using std::ostream;
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#define FLEX_DEBUG

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_accept[495] =
    {   0,
       88,   88,   81,   81,   96,   94,   93,   92,   94,   88,
       85,   94,   88,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   83,   81,   82,   83,    0,
       86,   87,   88,   84,   87,   79,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   25,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   81,   80,   22,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   24,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   74,   91,   64,
       91,   49,   91,   91,   91,   91,   91,   42,   91,   91,
       91,   91,   91,   91,   73,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,    2,   91,   23,
       91,   91,   91,   91,    5,   90,   91,   91,   91,   69,
       76,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   70,   38,   91,   39,   78,   91,   91,   91,   91,

       91,   91,   91,   40,   91,   46,   50,   59,   91,   91,
       91,   91,   91,   89,   91,    4,   91,   91,    7,   91,
       91,   91,   91,   91,   91,   91,   43,   91,   75,   91,
       91,   91,   91,   91,   91,   41,   91,   91,   91,   91,
       91,   91,   91,   71,   91,   60,   44,   91,   91,   91,
       35,    6,   91,    8,   26,   91,   91,   91,   91,   91,
       91,   91,   45,   91,   91,   91,   91,   51,   91,   91,
       91,   91,   91,   91,   77,   61,   62,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   68,   52,   67,   91,   91,   91,   91,

       91,   91,   91,   72,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   63,   53,   91,
       65,   57,   58,   91,   54,   91,   55,   56,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   47,   91,
       48,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,    3,   91,   91,   91,   91,   91,
       32,   91,   91,   91,   91,   91,   10,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,    1,   91,   91,
       91,   91,   30,   91,   91,   91,   91,   66,   91,   21,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   28,   91,   91,   91,   34,   37,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   19,   91,   36,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       17,   91,   91,   27,   91,   31,   33,   91,   91,   91,
       91,   91,   91,   16,   91,   91,   29,   91,   91,   12,
       91,   91,   15,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   11,   91,   91,   91,   20,   91,   91,   91,
       91,   91,   13,   91,   18,   91,   91,   91,   91,   91,
       91,    9,   14,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    1,
        1,    6,    1,    1,    7,    8,    9,   10,   11,   12,
       13,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,   14,    1,    1,   15,   16,   17,   18,   16,   19,
       20,   16,   21,   16,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   16,   32,   16,   16,   16,   16,
        1,    1,    1,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   16,   50,   51,   52,   53,   54,   55,   56,
       57,   58,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[498] =
    {   0,
        0,    0,   57,   62,  544,  545,  545,  545,  538,   59,
       64,  536,   70,   54,    0,  484,  506,  489,  492,  495,
       50,   70,  507,  501,   50,   49,   53,  486,  485,  490,
      486,  480,  491,   45,  490,  479,  492,  491,  485,   60,
       57,   65,   55,  489,  480,  545,  109,  545,  512,  515,
      514,  109,  115,  545,  119,  545,    0,  500,  465,  467,
      468,  469,  465,  478,  464,  460,  472,  483,  478,    0,
      454,  455,  457,  469,  446,  448,  448,   74,  457,  450,
      452,  445,  447,  460,  451,  443,   81,  434,  454,   86,
      443,  449,  435,  435,  437,  445,  431,  448,  423,  430,

      432,  422,  431,  427,  430,  437,  136,  545,    0,  420,
      427,  437,  419,  416,  428,  429,  422,  427,  446,    0,
      422,  420,  410,  408,  407,  420,  404,  423,  409,  403,
      408,  404,  399,  416,  395,  408,  394,    0,  408,    0,
      108,    0,  401,  393,  405,  391,  400,  402,   66,  401,
      110,  102,  400,  395,    0,  384,  397,  396,  380,  380,
      397,  388,  383,  390,  380,  388,  412,  373,  378,    0,
      409,  372,  372,  377,    0,    0,  384,  383,  383,    0,
        0,  365,  380,  361,  370,  370,  365,  359,  356,  355,
      355,    0,    0,  367,    0,    0,  370,  365,  352,  349,

      348,  351,  360,    0,  350,    0,    0,    0,  358,  354,
      342,  357,  350,    0,  354,    0,  372,  369,    0,  370,
      335,  336,  349,  332,  327,  330,    0,  334,    0,  328,
      327,  327,  326,  319,  333,    0,  322,  338,  322,  333,
      313,  327,  313,    0,  327,  134,    0,  318,  331,  328,
        0,    0,  313,    0,    0,  132,  336,  313,  318,  302,
      322,  300,    0,  318,  317,  305,  305,    0,  310,  299,
      303,  300,  300,  296,    0,    0,    0,  296,  293,  318,
      295,  117,  294,  303,  302,  301,  288,  303,  301,  285,
      283,  284,  294,    0,    0,    0,  293,  283,  284,  271,

      291,  288,  278,    0,  148,  282,  288,  269,  269,  265,
      274,  273,  260,  282,  267,  267,  270,    0,    0,  274,
        0,    0,    0,  269,    0,  272,    0,    0,  111,  268,
      266,  118,  254,  122,  258,  263,  256,  260,  253,  248,
      266,  254,  264,  262,  246,  246,  257,  255,    0,  240,
        0,  254,  127,  256,  238,  236,  239,  244,  238,  239,
      230,  231,  234,  242,    0,  245,  221,  235,  219,  227,
        0,  236,  225,  236,  214,  252,    0,  223,  221,  215,
      225,  216,  212,  226,  228,  214,  218,    0,  223,  206,
      206,  205,    0,  221,  204,  207,  200,    0,  194,    0,

      210,  215,  155,  210,  232,  198,  193,  207,  208,  190,
      193,    0,  198,  189,  186,    0,    0,  190,  198,  188,
      197,  195,  182,  182,  184,  187,    0,  186,    0,  177,
      178,  188,  167,  189,  195,  185,  183,  173,  166,  168,
        0,  162,  170,    0,  167,    0,    0,  167,  164,  173,
      183,  161,  151,    0,  169,  164,    0,  163,  153,    0,
      155,  148,    0,  174,  148,  163,  160,  155,  158,  147,
      137,  167,    0,  145,  164,  138,    0,  148,  130,  133,
      141,  131,    0,  131,    0,  134,  124,  128,  103,   72,
       53,    0,    0,  545,  184,  187,   59

    } ;

static yyconst short int yy_def[498] =
    {   0,
      494,    1,  495,  495,  494,  494,  494,  494,  496,  494,
      494,  494,  494,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  494,  494,  494,  494,  496,
      496,  494,  494,  494,  494,  494,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  494,  494,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,    0,  494,  494,  494

    } ;

static yyconst short int yy_nxt[604] =
    {   0,
        6,    7,    8,    7,    9,    6,   10,   11,   12,   13,
       13,   13,   13,    6,   14,   15,   15,   16,   17,   18,
       19,   15,   20,   21,   22,   23,   24,   15,   15,   25,
       26,   15,    6,   27,   28,   29,   30,   15,   31,   32,
       33,   34,   15,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   15,   44,   45,   15,   15,   15,   47,   48,
       47,   57,   49,   47,   48,   47,   52,   49,   53,   53,
       53,   53,   54,   55,   55,   55,   55,   52,   58,   53,
       53,   53,   53,   66,   68,   72,   75,   73,   77,   59,
       86,   87,  102,   93,   96,   69,  103,   67,   76,   78,

      197,   74,   60,  493,   97,   98,   99,   94,   79,   95,
      107,  104,  107,  128,  198,  129,  100,  101,   55,   55,
       55,   55,   52,  492,   53,   53,   53,   53,   55,   55,
       55,   55,  138,  142,  139,  143,  144,  107,  202,  107,
      189,  190,  200,  201,  276,  277,  282,  352,  283,  284,
      203,  356,  309,  285,  491,  359,  286,  353,  287,  360,
      288,  310,  329,  490,  330,  331,  377,  357,  378,  421,
      489,  488,  487,  486,  332,  333,  334,  335,  485,  336,
      484,  483,  482,  422,   46,   46,   46,   50,  481,   50,
      480,  479,  478,  477,  476,  475,  474,  473,  472,  471,

      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  438,  437,  436,  435,  434,  433,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,

      366,  365,  364,  363,  362,  361,  358,  355,  354,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  281,  280,  279,  278,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,

      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  199,  196,
      195,  194,  193,  192,  191,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  141,
      140,  137,  136,  135,  134,  133,  132,  131,  130,  127,

      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,   51,   51,
      108,  106,  105,   92,   91,   90,   89,   88,   85,   84,
       83,   82,   81,   80,   71,   70,   65,   64,   63,   62,
       61,   56,   51,  494,    5,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494
    } ;

static yyconst short int yy_chk[604] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,  497,    3,    4,    4,    4,   10,    4,   10,   10,
       10,   10,   10,   11,   11,   11,   11,   13,   14,   13,
       13,   13,   13,   21,   22,   25,   26,   25,   27,   14,
       34,   34,   43,   40,   41,   22,   43,   21,   26,   27,

      149,   25,   14,  491,   41,   42,   42,   40,   27,   40,
       47,   43,   47,   78,  149,   78,   42,   42,   52,   52,
       52,   52,   53,  490,   53,   53,   53,   53,   55,   55,
       55,   55,   87,   90,   87,   90,   90,  107,  152,  107,
      141,  141,  151,  151,  246,  246,  256,  329,  256,  256,
      152,  332,  282,  256,  489,  334,  256,  329,  256,  334,
      256,  282,  305,  488,  305,  305,  353,  332,  353,  403,
      487,  486,  484,  482,  305,  305,  305,  305,  481,  305,
      480,  479,  478,  403,  495,  495,  495,  496,  476,  496,
      475,  474,  472,  471,  470,  469,  468,  467,  466,  465,

      464,  462,  461,  459,  458,  456,  455,  453,  452,  451,
      450,  449,  448,  445,  443,  442,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  428,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  415,  414,  413,
      411,  410,  409,  408,  407,  406,  405,  404,  402,  401,
      399,  397,  396,  395,  394,  392,  391,  390,  389,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  376,
      375,  374,  373,  372,  370,  369,  368,  367,  366,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      352,  350,  348,  347,  346,  345,  344,  343,  342,  341,

      340,  339,  338,  337,  336,  335,  333,  331,  330,  326,
      324,  320,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  303,  302,  301,  300,  299,  298,
      297,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  281,  280,  279,  278,  274,  273,  272,  271,
      270,  269,  267,  266,  265,  264,  262,  261,  260,  259,
      258,  257,  253,  250,  249,  248,  245,  243,  242,  241,
      240,  239,  238,  237,  235,  234,  233,  232,  231,  230,
      228,  226,  225,  224,  223,  222,  221,  220,  218,  217,
      215,  213,  212,  211,  210,  209,  205,  203,  202,  201,

      200,  199,  198,  197,  194,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  179,  178,  177,  174,  173,
      172,  171,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  154,  153,  150,  148,
      147,  146,  145,  144,  143,  139,  137,  136,  135,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   91,   89,
       88,   86,   85,   84,   83,   82,   81,   80,   79,   77,

       76,   75,   74,   73,   72,   71,   69,   68,   67,   66,
       65,   64,   63,   62,   61,   60,   59,   58,   51,   50,
       49,   45,   44,   39,   38,   37,   36,   35,   33,   32,
       31,   30,   29,   28,   24,   23,   20,   19,   18,   17,
       16,   12,    9,    5,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494
    } ;

static yyconst short int yy_rule_linenum[95] =
    {   0,
       17,   18,   19,   20,   21,   22,   23,   24,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   40,   41,   42,   43,   44,   46,   47,   48,   49,
       50,   51,   52,   53,   55,   56,   57,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
       83,   84,   85,   86,   87,   88,   89,   90,   91,   92,
       93,   94,   95,   97,   98,   99,  100,  101,  103,  104,
      105,  106,  107,  109,  110,  111,  112,  113,  114,  115,
      116,  117,  118,  119

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "Kernel/Parsers/MSLScanner.l"
#define INITIAL 0
#line 5 "Kernel/Parsers/MSLScanner.l"
#include <Kernel/Parsers/MSLParser.h>
using namespace std;
#define COMMENT 1

#line 653 "Kernel/Parsers/MSLScanner.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 "Kernel/Parsers/MSLScanner.l"


#line 783 "Kernel/Parsers/MSLScanner.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 495 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 545 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				cerr << "--scanner backing up\n";
			else if ( yy_act < 95 )
				cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 95 )
				cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 96 )
				cerr << "--(end of buffer or a NUL)\n";
			else
				cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 17 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::APPLICATION;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAOMARK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAOMARKSGROUP;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAORENDERABLE2DIMAGE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 21 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAORENDERABLE2DTEXT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 22 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAORENDERABLE3DLINE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAORENDERABLE3DMODEL;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MAORENDERABLE3DPATH;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORADDDYNAMICOBJECT;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORANG;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORCHANGEPOSE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORDISTANCE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORPATHADDPOINT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORPATHREMOVEPOINTS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORPROPERTY;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORQUITAPP;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORRANDOM;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORRELATIVEPOSE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORSOUND;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORVISIBILITY;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBACTUATORANIM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBCONTROLLERAND;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBCONTROLLERNAND;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBCONTROLLERNOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBCONTROLLEROR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBCONTROLLERSCRIPT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORACTUATOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORALWAYS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORCOLLISION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORDELAY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORKEYBOARD;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORNEAR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORPROPERTY;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::MLBSENSORRANDOM;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::GROUND;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::DYNAMICOBJECT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::STATICOBJECT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_NAME;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_PATH;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 62 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_SIZE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 63 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_MARKS;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_POS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_COLOR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_WIDTH;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_HEIGHT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_TEXT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 69 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_ANIM_TYPE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 70 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_REFERENCE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 71 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_MAO;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_TIME;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 73 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_OFFSET;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 74 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_IMPULSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_ANG_AXIS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 76 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_PROPERTY;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 77 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_ROT_TYPE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 78 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_ROTATION;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 79 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_LOC_TYPE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 80 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_LOCATION;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 81 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_TYPE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 82 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_VALUE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_VALUE1;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_VALUE2;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_ACTUATOR;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_KEY;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_DISTANCE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_PROBABILITY;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 89 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_INVERSE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_GRAVITY;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_AXIS;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 92 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_MASS;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 93 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_SHAPE;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_SHADOWS;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::PARAM_SUN;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::T_INTEGER;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::T_FLOAT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::T_BOOL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::T_STRING;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::T_POSE;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 103 "Kernel/Parsers/MSLScanner.l"
{BEGIN(COMMENT);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 104 "Kernel/Parsers/MSLScanner.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 "Kernel/Parsers/MSLScanner.l"
{}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 106 "Kernel/Parsers/MSLScanner.l"
{yylineno++;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 107 "Kernel/Parsers/MSLScanner.l"
{}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 109 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::ARROW;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 110 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::DOT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 111 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::STRING;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 112 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::FLOAT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 113 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::INTEGER;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 114 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::BOOL;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 115 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::BOOL;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 116 "Kernel/Parsers/MSLScanner.l"
{return MSLParser::IDENTIFIER;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 117 "Kernel/Parsers/MSLScanner.l"
{yylineno++;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 118 "Kernel/Parsers/MSLScanner.l"
{/*Ignore every blank space*/}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 119 "Kernel/Parsers/MSLScanner.l"
{/*Any other literal, just return it! */ return yytext[0];}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
#line 120 "Kernel/Parsers/MSLScanner.l"
{yyterminate();}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 122 "Kernel/Parsers/MSLScanner.l"
ECHO;
	YY_BREAK
#line 1360 "Kernel/Parsers/MSLScanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 495 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 495 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 494);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 122 "Kernel/Parsers/MSLScanner.l"

